<?php
if ( PHP_SAPI !== 'cli' ) {
	http_response_code( 404 );
	exit;
}

/** Focused source-contract regressions for ML-PROP-007. */

function expect_property_url_routing( $condition, $label ) {
	if ( ! $condition ) {
		fwrite( STDERR, "FAIL {$label}\n" );
		exit( 1 );
	}
}

$theme   = dirname( __DIR__ );
$archive = file_get_contents( $theme . '/archive-property.php' );
$single  = file_get_contents( $theme . '/single-property.php' );
$card    = file_get_contents( $theme . '/parts/property-card-v2.php' );
$related = file_get_contents( $theme . '/parts/related-taxonomy-card.php' );
$router  = file_get_contents( dirname( $theme, 2 ) . '/plugins/pera-multilingual/includes/class-router.php' );
$ajax    = file_get_contents( dirname( $theme, 2 ) . '/plugins/pera-multilingual/includes/class-ajax.php' );
$header_helpers = file_get_contents( $theme . '/inc/theme-helpers.php' );

foreach ( array( '/contact-us/', '/book-a-consultancy/', '/citizenship-by-investment/' ) as $path ) {
	$call = "pera_ml_url( home_url( '{$path}' ) )";
	expect_property_url_routing( false !== strpos( $archive, $call ), "archive CTA {$path} uses Pera ML routing" );
}

foreach ( array( 'besiktas', 'sisli', 'kadikoy' ) as $district ) {
	$call = "pera_ml_url( home_url( '/district/istanbul/{$district}/' ) )";
	expect_property_url_routing( false !== strpos( $archive, $call ), "archive district {$district} uses Pera ML routing" );
}

expect_property_url_routing( false !== strpos( $archive, 'pera_ml_url( $archive_base_url )' ), 'archive form and pagination base preserves language' );
expect_property_url_routing( false !== strpos( $single, "pera_ml_url( home_url( '/sell-your-istanbul-real-estate/' ) )" ), 'single sales CTA preserves language' );
expect_property_url_routing( false !== strpos( $single, "pera_ml_url( home_url( '/rent-your-istanbul-real-estate/' ) )" ), 'single rental CTA preserves language' );

// WordPress already routes these calls through the canonical router filters.
foreach ( array( "add_filter( 'post_type_link'", "add_filter( 'term_link'" ) as $filter ) {
	expect_property_url_routing( false !== strpos( $router, $filter ), "router owns {$filter}" );
}
expect_property_url_routing( false !== strpos( $card, 'get_permalink( $post_id )' ), 'property-card navigation uses filtered property permalink' );
expect_property_url_routing( false !== strpos( $card, 'get_term_link( $district_term )' ), 'property-card district navigation uses filtered term link' );
expect_property_url_routing( false !== strpos( $related, 'get_term_link( $term )' ), 'related taxonomy navigation uses filtered term link' );
expect_property_url_routing( false !== strpos( $single, 'get_permalink( $property_id )' ), 'single property form context uses filtered permalink' );

// AJAX establishes the posted language before shared cards are rendered.
expect_property_url_routing( false !== strpos( $ajax, 'set_request_language( $language )' ), 'AJAX property cards inherit the requested language' );
expect_property_url_routing( false !== strpos( $archive, "fd.set('pera_ml_lang', peraMlLanguage)" ), 'archive sends active language to AJAX' );

// Header/home navigation is generated by the shared helper; these templates do not emit a second breadcrumb implementation.
expect_property_url_routing( false !== strpos( $header_helpers, "'home_url'      => function_exists( 'pera_ml_home_url' ) ? pera_ml_home_url()" ), 'shared home and breadcrumb-level navigation preserves language' );
foreach ( array( $archive, $single, $card, $related ) as $property_source ) {
	foreach ( array( '/de/de/', '/zh/zh/', '/ar/ar/' ) as $double_prefix ) {
		expect_property_url_routing( false === strpos( $property_source, $double_prefix ), 'modified property paths contain no manual double prefix' );
	}
}

echo "Multilingual property URL routing tests passed\n";
